version: "3.9"
services:
 app-react:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: app-react
   restart: always
   ports:
     - 4000:4000
   volumes:
     - .:/app
     - /app/node_modules
   networks:
     - network

networks:
 network: